threatProject/threatProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('threatapp/',include('threatapp.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

threatProject/threatapp/urls.py
from django.urls import path

from . import views

app_name = 'threatapp'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('uploadfile/', views.uploadfile, name='uploadfile'),
    path('checkupdate/', views.checkupdate, name='checkupdate'),
]

threatProject/threatapp/models.py
from django.db import models

class Threat(models.Model):
    date = models.DateTimeField('record date')
    filename = models.CharField(max_length=128)
    action = models.CharField(max_length=128)
    submit_type = models.CharField(max_length=128)
    rating = models.CharField(max_length=128)
			
    def __str__(self):
        return self.filename

class MetaFile(models.Model):
    filename = models.CharField(max_length=128)
    is_imported = models.BooleanField()
    
    def __str__(self):
        return self.filename

threatProject/threatapp/views.py
import json, os, sys
from datetime import datetime
from django.http import HttpResponseRedirect, JsonResponse
from django.views import generic
from django.urls import reverse
from .models import Threat, MetaFile
from django.core.files.storage import FileSystemStorage
from django.conf import settings

# for displaying table of threats, default order by date
class IndexView(generic.ListView):
    template_name = 'threatapp/index.html'
    context_object_name = 'threats_list'
    paginate_by = 20
    
    def get_queryset(self):
        order_by = self.request.GET.get('order_by', 'date')
        return Threat.objects.order_by(order_by)

# user can upload json meta file to add threats to database
def uploadfile(request):
    if request.method == 'POST' and request.FILES['threatfile']:
        if request.is_ajax():
            threatfile = request.FILES['threatfile']
            try:
                # save file to media dir
                fs = FileSystemStorage()
                filename = fs.save(threatfile.name, threatfile)
                data = updateDatabase(threatfile)
                MetaFile.objects.create(filename=filename,is_imported=False)
                response = {"data": data}
                return JsonResponse(response)
            except:
                return JsonResponse({"status":'false',"message":sys.exc_info()[0]}, status=500)
    return HttpResponseRedirect(reverse('threatapp:index'))

# check for unprocessed meta file in folder and
# notify dom to update
def checkupdate(request):
    if request.method == 'GET':
        fs = FileSystemStorage(settings.MEDIA_ROOT)
        data = []
        for root, dirs, files in os.walk(settings.MEDIA_ROOT):
            for file in files:
                if file.endswith(".json"):
                    file_record = MetaFile.objects.filter(filename=file).count()
                    if file_record == 0:
                        threatfile = fs.open(file)
                        data += updateDatabase(threatfile)
                        MetaFile.objects.create(filename=file,is_imported=True)
        return JsonResponse({"data": data})

def updateDatabase(threatfile):
    data = []
    for chunk in threatfile.chunks():
        data_chunk = json.loads(chunk.decode('utf-8').replace("'",'"'))
        data+=data_chunk
        for threat in data_chunk:
            Threat.objects.update_or_create(date=datetime.strptime(threat['date'],'%b %d, %Y %H:%M:%S'), filename=threat['filename'],
            action=threat['action'],submit_type=threat['submit-type'],rating=threat['rating'])
    return data

threatProject/threatapp/templates/threatapp/index.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'threatapp/style.css' %}" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="http://code.jquery.com/jquery-2.1.4.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js"></script>
    <script src="{% static 'threatapp/javascript/threatapp_controller.js' %}"></script>
</head>
<body>
    <div class="threat-table-container table-responsive">
        {% if threats_list %}
        <table class="table">
            <thead>
                <tr>
                    <th><a href="?order_by=filename">File Name</a></th>
                    <th><a href="?order_by=submit_type">Submit Type</a></th>
                    <th><a href="?order_by=action">Action</a></th>
                    <th><a href="?order_by=rating">Rating</a></th>
                    <th><a href="?order_by=date">Date</a></th>
                </tr>
            </thead>
            <tbody>
                {% for threat in threats_list %}
                <tr class="{{ threat.rating }}">
                    <td>{{ threat.filename }}</td>
                    <td>{{ threat.submit_type }}</td>
                    <td>{{ threat.action }}</td>
                    <td>{{ threat.rating }}</td>
                    <td>{{ threat.date }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% else %}
            <p>No threats are available.</p>
        {% endif %}
    
        {% block pagination %}
        {% if is_paginated %}
            <div class="pagination">
                <span class="page-links">
                    {% if page_obj.has_previous %}
                        <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}" class="btn btn-default">previous</a>
                    {% endif %}
                    <span class="page-current">
                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                    </span>
                    {% if page_obj.has_next %}
                        <a href="{{ request.path }}?page={{ page_obj.next_page_number }}" class="btn btn-default">next</a>
                    {% endif %}
                </span>
            </div>
        {% endif %}
        {% endblock %}
    </div>
    <div class="threat-upload-container">
        <form action="{% url 'threatapp:uploadfile' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <label class="btn btn-primary" for="threatfile">
                <input id="threatfile" type="file" name="threatfile" accept="file_extension" data-url="{% url 'threatapp:uploadfile' %} " style="display:none;">
                Choose a JSON File
            </label>
            
            <button id="uploadfile" type="submit" class="btn btn-default"/>Upload</button>
        </form>
    </div>
</body>
</html>